import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import Navbar from '@/components/Navbar'
import { UserProvider } from '../context/UserContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'CMU GE',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <Navbar />
                    { children }
                </UserProvider>
            </body>
        </html>
    );
}
